modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="ruby"
version="1.01.19"
displayName="Ruby"
credits="In the future, there will be the development of a full version of the mod with dimensions, mobs, etc."
displayURL="https://modrinth.com/mod/icez"
logoFile="logo.png"
authors="FaNaTiK_IceZ"
description='''
A mod that adds a new ore that will combine the best characteristics of non-cerite and gold items
'''

[[dependencies.ruby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ruby]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.47]"
    ordering="NONE"
    side="BOTH"



