modLoader="javafml"
loaderVersion="[36,)"
license="Apache License version 2.0"

[[mods]]
modId="rubin"
version="Alpha"
displayName="Rubin lite"
credits="Мод в альфа версии"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="FaNaTiK_IceZ"

[[dependencies.rubin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.rubin]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20]"
    ordering="NONE"
    side="BOTH"


[[dependencies.rubin]]
    modId="just_enough_items-1.16.5"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubin]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

